#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 05 21:29:01 IST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto cf69534c6b8d41bf9872f3dbfc2a5aa1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot execute_tb4_behav xil_defaultlib.execute_tb4 xil_defaultlib.glbl -log elaborate.log"
xelab -wto cf69534c6b8d41bf9872f3dbfc2a5aa1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot execute_tb4_behav xil_defaultlib.execute_tb4 xil_defaultlib.glbl -log elaborate.log

